apiVersion: apps/v1
kind: Deployment

metadata:
  name: controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      name: controller
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        imagePullPolicy: Always
        image: gcr.io/edcop-dev/mbaker:v4
        envFrom:
          - configMapRef:
              name: controller-config
      restartPolicy: Always
      dnsPolicy: ClusterFirst
