apiVersion: apps/v1
kind: Deployment

metadata:
  name: monitor
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      name: monitor
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        imagePullPolicy: Always
        image: gcr.io/edcop-dev/mbaker:v1
      restartPolicy: Always
      dnsPolicy: ClusterFirst