apiVersion: v1
kind: ConfigMap
metadata:
  name: trox-map
  namespace: kube-system
data:
  ip: {{ quote .Values.settings.ip }}
  tap_type: {{ quote .Values.settings.tap_type }}
  app_label: {{ quote .Values.settings.app_label }}
  timeout: {{ quote .Values.settings.timeout }}
