apiVersion: v1
kind: Secret
metadata:
  name: trox-secret
  namespace: kube-system
data:
  username: {{ .Values.tap_credentials.username | b64enc }}
  password: {{ .Values.tap_credentials.password | b64enc }}
