apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: troxileia
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get" , "list" , "watch"]

- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch",]

- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
